apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akslihidemo-b05c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akslihidemo-b05c"
  template:
    metadata:
      labels:
        app: "akslihidemo-b05c"
    spec:
      containers:
        - name: "akslihidemo-b05c"
          image: "crlihi101.azurecr.io/akslihidemo"
          ports:
          - containerPort: 80