apiVersion: v1
kind: Service
metadata:
    name: "akslihidemo-b05c"
    labels:
        app: "akslihidemo-b05c"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akslihidemo-b05c"