on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crlihi101.azurecr.io
        username: ${{ secrets.acr_crlihi101_username }}
        password: ${{ secrets.acr_crlihi101_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crlihi101.azurecr.io/akslihidemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crlihi101.azurecr.io/akslihidemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akslihidemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-lihi-demo8777 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-lihi-demo8777`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-lihi-demo8777
        container-registry-url: crlihi101.azurecr.io
        container-registry-username: ${{ secrets.acr_crlihi101_username }}
        container-registry-password: ${{ secrets.acr_crlihi101_password }}
        secret-name: akslihidemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-lihi-demo8777
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          crlihi101.azurecr.io/akslihidemo:${{ github.sha }}
        imagepullsecrets: |
          akslihidemodockerauth
